// Generated by gencpp from file i2c_pkg/BatteryLevelSrvRequest.msg
// DO NOT EDIT!


#ifndef I2C_PKG_MESSAGE_BATTERYLEVELSRVREQUEST_H
#define I2C_PKG_MESSAGE_BATTERYLEVELSRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace i2c_pkg
{
template <class ContainerAllocator>
struct BatteryLevelSrvRequest_
{
  typedef BatteryLevelSrvRequest_<ContainerAllocator> Type;

  BatteryLevelSrvRequest_()
    {
    }
  BatteryLevelSrvRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::i2c_pkg::BatteryLevelSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::i2c_pkg::BatteryLevelSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct BatteryLevelSrvRequest_

typedef ::i2c_pkg::BatteryLevelSrvRequest_<std::allocator<void> > BatteryLevelSrvRequest;

typedef boost::shared_ptr< ::i2c_pkg::BatteryLevelSrvRequest > BatteryLevelSrvRequestPtr;
typedef boost::shared_ptr< ::i2c_pkg::BatteryLevelSrvRequest const> BatteryLevelSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::i2c_pkg::BatteryLevelSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::i2c_pkg::BatteryLevelSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace i2c_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::i2c_pkg::BatteryLevelSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::i2c_pkg::BatteryLevelSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::i2c_pkg::BatteryLevelSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::i2c_pkg::BatteryLevelSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::i2c_pkg::BatteryLevelSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::i2c_pkg::BatteryLevelSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::i2c_pkg::BatteryLevelSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::i2c_pkg::BatteryLevelSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::i2c_pkg::BatteryLevelSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "i2c_pkg/BatteryLevelSrvRequest";
  }

  static const char* value(const ::i2c_pkg::BatteryLevelSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::i2c_pkg::BatteryLevelSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::i2c_pkg::BatteryLevelSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::i2c_pkg::BatteryLevelSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BatteryLevelSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::i2c_pkg::BatteryLevelSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::i2c_pkg::BatteryLevelSrvRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // I2C_PKG_MESSAGE_BATTERYLEVELSRVREQUEST_H
