// Generated by gencpp from file i2c_pkg/BatteryLevelSrv.msg
// DO NOT EDIT!


#ifndef I2C_PKG_MESSAGE_BATTERYLEVELSRV_H
#define I2C_PKG_MESSAGE_BATTERYLEVELSRV_H

#include <ros/service_traits.h>


#include <i2c_pkg/BatteryLevelSrvRequest.h>
#include <i2c_pkg/BatteryLevelSrvResponse.h>


namespace i2c_pkg
{

struct BatteryLevelSrv
{

typedef BatteryLevelSrvRequest Request;
typedef BatteryLevelSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BatteryLevelSrv
} // namespace i2c_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::i2c_pkg::BatteryLevelSrv > {
  static const char* value()
  {
    return "ded14a708dd5929a9ebf864ad17c94f5";
  }

  static const char* value(const ::i2c_pkg::BatteryLevelSrv&) { return value(); }
};

template<>
struct DataType< ::i2c_pkg::BatteryLevelSrv > {
  static const char* value()
  {
    return "i2c_pkg/BatteryLevelSrv";
  }

  static const char* value(const ::i2c_pkg::BatteryLevelSrv&) { return value(); }
};


// service_traits::MD5Sum< ::i2c_pkg::BatteryLevelSrvRequest> should match 
// service_traits::MD5Sum< ::i2c_pkg::BatteryLevelSrv > 
template<>
struct MD5Sum< ::i2c_pkg::BatteryLevelSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::i2c_pkg::BatteryLevelSrv >::value();
  }
  static const char* value(const ::i2c_pkg::BatteryLevelSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::i2c_pkg::BatteryLevelSrvRequest> should match 
// service_traits::DataType< ::i2c_pkg::BatteryLevelSrv > 
template<>
struct DataType< ::i2c_pkg::BatteryLevelSrvRequest>
{
  static const char* value()
  {
    return DataType< ::i2c_pkg::BatteryLevelSrv >::value();
  }
  static const char* value(const ::i2c_pkg::BatteryLevelSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::i2c_pkg::BatteryLevelSrvResponse> should match 
// service_traits::MD5Sum< ::i2c_pkg::BatteryLevelSrv > 
template<>
struct MD5Sum< ::i2c_pkg::BatteryLevelSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::i2c_pkg::BatteryLevelSrv >::value();
  }
  static const char* value(const ::i2c_pkg::BatteryLevelSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::i2c_pkg::BatteryLevelSrvResponse> should match 
// service_traits::DataType< ::i2c_pkg::BatteryLevelSrv > 
template<>
struct DataType< ::i2c_pkg::BatteryLevelSrvResponse>
{
  static const char* value()
  {
    return DataType< ::i2c_pkg::BatteryLevelSrv >::value();
  }
  static const char* value(const ::i2c_pkg::BatteryLevelSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // I2C_PKG_MESSAGE_BATTERYLEVELSRV_H
