// Generated by gencpp from file ctrl_pkg/ActiveStateSrvRequest.msg
// DO NOT EDIT!


#ifndef CTRL_PKG_MESSAGE_ACTIVESTATESRVREQUEST_H
#define CTRL_PKG_MESSAGE_ACTIVESTATESRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ctrl_pkg
{
template <class ContainerAllocator>
struct ActiveStateSrvRequest_
{
  typedef ActiveStateSrvRequest_<ContainerAllocator> Type;

  ActiveStateSrvRequest_()
    : state(0)  {
    }
  ActiveStateSrvRequest_(const ContainerAllocator& _alloc)
    : state(0)  {
  (void)_alloc;
    }



   typedef int8_t _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::ctrl_pkg::ActiveStateSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ctrl_pkg::ActiveStateSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ActiveStateSrvRequest_

typedef ::ctrl_pkg::ActiveStateSrvRequest_<std::allocator<void> > ActiveStateSrvRequest;

typedef boost::shared_ptr< ::ctrl_pkg::ActiveStateSrvRequest > ActiveStateSrvRequestPtr;
typedef boost::shared_ptr< ::ctrl_pkg::ActiveStateSrvRequest const> ActiveStateSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ctrl_pkg::ActiveStateSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ctrl_pkg::ActiveStateSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ctrl_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ctrl_pkg': ['/home/deepracer/catkin_ws/src/ctrl_pkg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ctrl_pkg::ActiveStateSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ctrl_pkg::ActiveStateSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ctrl_pkg::ActiveStateSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ctrl_pkg::ActiveStateSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ctrl_pkg::ActiveStateSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ctrl_pkg::ActiveStateSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ctrl_pkg::ActiveStateSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a33bed68685ae53bd39b0a9242210752";
  }

  static const char* value(const ::ctrl_pkg::ActiveStateSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa33bed68685ae53bULL;
  static const uint64_t static_value2 = 0xd39b0a9242210752ULL;
};

template<class ContainerAllocator>
struct DataType< ::ctrl_pkg::ActiveStateSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ctrl_pkg/ActiveStateSrvRequest";
  }

  static const char* value(const ::ctrl_pkg::ActiveStateSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ctrl_pkg::ActiveStateSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 state\n\
";
  }

  static const char* value(const ::ctrl_pkg::ActiveStateSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ctrl_pkg::ActiveStateSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActiveStateSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ctrl_pkg::ActiveStateSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ctrl_pkg::ActiveStateSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<int8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CTRL_PKG_MESSAGE_ACTIVESTATESRVREQUEST_H
