// Generated by gencpp from file ctrl_pkg/ActiveStateSrv.msg
// DO NOT EDIT!


#ifndef CTRL_PKG_MESSAGE_ACTIVESTATESRV_H
#define CTRL_PKG_MESSAGE_ACTIVESTATESRV_H

#include <ros/service_traits.h>


#include <ctrl_pkg/ActiveStateSrvRequest.h>
#include <ctrl_pkg/ActiveStateSrvResponse.h>


namespace ctrl_pkg
{

struct ActiveStateSrv
{

typedef ActiveStateSrvRequest Request;
typedef ActiveStateSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ActiveStateSrv
} // namespace ctrl_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ctrl_pkg::ActiveStateSrv > {
  static const char* value()
  {
    return "c83aa8233d546528849971b5100ae7d6";
  }

  static const char* value(const ::ctrl_pkg::ActiveStateSrv&) { return value(); }
};

template<>
struct DataType< ::ctrl_pkg::ActiveStateSrv > {
  static const char* value()
  {
    return "ctrl_pkg/ActiveStateSrv";
  }

  static const char* value(const ::ctrl_pkg::ActiveStateSrv&) { return value(); }
};


// service_traits::MD5Sum< ::ctrl_pkg::ActiveStateSrvRequest> should match 
// service_traits::MD5Sum< ::ctrl_pkg::ActiveStateSrv > 
template<>
struct MD5Sum< ::ctrl_pkg::ActiveStateSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ctrl_pkg::ActiveStateSrv >::value();
  }
  static const char* value(const ::ctrl_pkg::ActiveStateSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ctrl_pkg::ActiveStateSrvRequest> should match 
// service_traits::DataType< ::ctrl_pkg::ActiveStateSrv > 
template<>
struct DataType< ::ctrl_pkg::ActiveStateSrvRequest>
{
  static const char* value()
  {
    return DataType< ::ctrl_pkg::ActiveStateSrv >::value();
  }
  static const char* value(const ::ctrl_pkg::ActiveStateSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ctrl_pkg::ActiveStateSrvResponse> should match 
// service_traits::MD5Sum< ::ctrl_pkg::ActiveStateSrv > 
template<>
struct MD5Sum< ::ctrl_pkg::ActiveStateSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ctrl_pkg::ActiveStateSrv >::value();
  }
  static const char* value(const ::ctrl_pkg::ActiveStateSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ctrl_pkg::ActiveStateSrvResponse> should match 
// service_traits::DataType< ::ctrl_pkg::ActiveStateSrv > 
template<>
struct DataType< ::ctrl_pkg::ActiveStateSrvResponse>
{
  static const char* value()
  {
    return DataType< ::ctrl_pkg::ActiveStateSrv >::value();
  }
  static const char* value(const ::ctrl_pkg::ActiveStateSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CTRL_PKG_MESSAGE_ACTIVESTATESRV_H
