// Generated by gencpp from file ctrl_pkg/EnableStateSrvRequest.msg
// DO NOT EDIT!


#ifndef CTRL_PKG_MESSAGE_ENABLESTATESRVREQUEST_H
#define CTRL_PKG_MESSAGE_ENABLESTATESRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ctrl_pkg
{
template <class ContainerAllocator>
struct EnableStateSrvRequest_
{
  typedef EnableStateSrvRequest_<ContainerAllocator> Type;

  EnableStateSrvRequest_()
    : isActive(false)  {
    }
  EnableStateSrvRequest_(const ContainerAllocator& _alloc)
    : isActive(false)  {
  (void)_alloc;
    }



   typedef uint8_t _isActive_type;
  _isActive_type isActive;





  typedef boost::shared_ptr< ::ctrl_pkg::EnableStateSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ctrl_pkg::EnableStateSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct EnableStateSrvRequest_

typedef ::ctrl_pkg::EnableStateSrvRequest_<std::allocator<void> > EnableStateSrvRequest;

typedef boost::shared_ptr< ::ctrl_pkg::EnableStateSrvRequest > EnableStateSrvRequestPtr;
typedef boost::shared_ptr< ::ctrl_pkg::EnableStateSrvRequest const> EnableStateSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ctrl_pkg::EnableStateSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ctrl_pkg::EnableStateSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ctrl_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ctrl_pkg': ['/home/deepracer/catkin_ws/src/ctrl_pkg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ctrl_pkg::EnableStateSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ctrl_pkg::EnableStateSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ctrl_pkg::EnableStateSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ctrl_pkg::EnableStateSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ctrl_pkg::EnableStateSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ctrl_pkg::EnableStateSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ctrl_pkg::EnableStateSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "74c71bbe95320ceee0e02ceb6900a4a1";
  }

  static const char* value(const ::ctrl_pkg::EnableStateSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x74c71bbe95320ceeULL;
  static const uint64_t static_value2 = 0xe0e02ceb6900a4a1ULL;
};

template<class ContainerAllocator>
struct DataType< ::ctrl_pkg::EnableStateSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ctrl_pkg/EnableStateSrvRequest";
  }

  static const char* value(const ::ctrl_pkg::EnableStateSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ctrl_pkg::EnableStateSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool isActive\n\
";
  }

  static const char* value(const ::ctrl_pkg::EnableStateSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ctrl_pkg::EnableStateSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.isActive);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EnableStateSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ctrl_pkg::EnableStateSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ctrl_pkg::EnableStateSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "isActive: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isActive);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CTRL_PKG_MESSAGE_ENABLESTATESRVREQUEST_H
