// Generated by gencpp from file ctrl_pkg/EnableStateSrv.msg
// DO NOT EDIT!


#ifndef CTRL_PKG_MESSAGE_ENABLESTATESRV_H
#define CTRL_PKG_MESSAGE_ENABLESTATESRV_H

#include <ros/service_traits.h>


#include <ctrl_pkg/EnableStateSrvRequest.h>
#include <ctrl_pkg/EnableStateSrvResponse.h>


namespace ctrl_pkg
{

struct EnableStateSrv
{

typedef EnableStateSrvRequest Request;
typedef EnableStateSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EnableStateSrv
} // namespace ctrl_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ctrl_pkg::EnableStateSrv > {
  static const char* value()
  {
    return "232cd2b9458497f0f728a51b5639d139";
  }

  static const char* value(const ::ctrl_pkg::EnableStateSrv&) { return value(); }
};

template<>
struct DataType< ::ctrl_pkg::EnableStateSrv > {
  static const char* value()
  {
    return "ctrl_pkg/EnableStateSrv";
  }

  static const char* value(const ::ctrl_pkg::EnableStateSrv&) { return value(); }
};


// service_traits::MD5Sum< ::ctrl_pkg::EnableStateSrvRequest> should match 
// service_traits::MD5Sum< ::ctrl_pkg::EnableStateSrv > 
template<>
struct MD5Sum< ::ctrl_pkg::EnableStateSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ctrl_pkg::EnableStateSrv >::value();
  }
  static const char* value(const ::ctrl_pkg::EnableStateSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ctrl_pkg::EnableStateSrvRequest> should match 
// service_traits::DataType< ::ctrl_pkg::EnableStateSrv > 
template<>
struct DataType< ::ctrl_pkg::EnableStateSrvRequest>
{
  static const char* value()
  {
    return DataType< ::ctrl_pkg::EnableStateSrv >::value();
  }
  static const char* value(const ::ctrl_pkg::EnableStateSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ctrl_pkg::EnableStateSrvResponse> should match 
// service_traits::MD5Sum< ::ctrl_pkg::EnableStateSrv > 
template<>
struct MD5Sum< ::ctrl_pkg::EnableStateSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ctrl_pkg::EnableStateSrv >::value();
  }
  static const char* value(const ::ctrl_pkg::EnableStateSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ctrl_pkg::EnableStateSrvResponse> should match 
// service_traits::DataType< ::ctrl_pkg::EnableStateSrv > 
template<>
struct DataType< ::ctrl_pkg::EnableStateSrvResponse>
{
  static const char* value()
  {
    return DataType< ::ctrl_pkg::EnableStateSrv >::value();
  }
  static const char* value(const ::ctrl_pkg::EnableStateSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CTRL_PKG_MESSAGE_ENABLESTATESRV_H
