// Generated by gencpp from file ctrl_pkg/ModelStateSrv.msg
// DO NOT EDIT!


#ifndef CTRL_PKG_MESSAGE_MODELSTATESRV_H
#define CTRL_PKG_MESSAGE_MODELSTATESRV_H

#include <ros/service_traits.h>


#include <ctrl_pkg/ModelStateSrvRequest.h>
#include <ctrl_pkg/ModelStateSrvResponse.h>


namespace ctrl_pkg
{

struct ModelStateSrv
{

typedef ModelStateSrvRequest Request;
typedef ModelStateSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ModelStateSrv
} // namespace ctrl_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ctrl_pkg::ModelStateSrv > {
  static const char* value()
  {
    return "ccd9fcb55e6e203501cbffcaff851b4f";
  }

  static const char* value(const ::ctrl_pkg::ModelStateSrv&) { return value(); }
};

template<>
struct DataType< ::ctrl_pkg::ModelStateSrv > {
  static const char* value()
  {
    return "ctrl_pkg/ModelStateSrv";
  }

  static const char* value(const ::ctrl_pkg::ModelStateSrv&) { return value(); }
};


// service_traits::MD5Sum< ::ctrl_pkg::ModelStateSrvRequest> should match 
// service_traits::MD5Sum< ::ctrl_pkg::ModelStateSrv > 
template<>
struct MD5Sum< ::ctrl_pkg::ModelStateSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ctrl_pkg::ModelStateSrv >::value();
  }
  static const char* value(const ::ctrl_pkg::ModelStateSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ctrl_pkg::ModelStateSrvRequest> should match 
// service_traits::DataType< ::ctrl_pkg::ModelStateSrv > 
template<>
struct DataType< ::ctrl_pkg::ModelStateSrvRequest>
{
  static const char* value()
  {
    return DataType< ::ctrl_pkg::ModelStateSrv >::value();
  }
  static const char* value(const ::ctrl_pkg::ModelStateSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ctrl_pkg::ModelStateSrvResponse> should match 
// service_traits::MD5Sum< ::ctrl_pkg::ModelStateSrv > 
template<>
struct MD5Sum< ::ctrl_pkg::ModelStateSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ctrl_pkg::ModelStateSrv >::value();
  }
  static const char* value(const ::ctrl_pkg::ModelStateSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ctrl_pkg::ModelStateSrvResponse> should match 
// service_traits::DataType< ::ctrl_pkg::ModelStateSrv > 
template<>
struct DataType< ::ctrl_pkg::ModelStateSrvResponse>
{
  static const char* value()
  {
    return DataType< ::ctrl_pkg::ModelStateSrv >::value();
  }
  static const char* value(const ::ctrl_pkg::ModelStateSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CTRL_PKG_MESSAGE_MODELSTATESRV_H
