// Generated by gencpp from file ctrl_pkg/NavThrottleSrvResponse.msg
// DO NOT EDIT!


#ifndef CTRL_PKG_MESSAGE_NAVTHROTTLESRVRESPONSE_H
#define CTRL_PKG_MESSAGE_NAVTHROTTLESRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ctrl_pkg
{
template <class ContainerAllocator>
struct NavThrottleSrvResponse_
{
  typedef NavThrottleSrvResponse_<ContainerAllocator> Type;

  NavThrottleSrvResponse_()
    : error(0)  {
    }
  NavThrottleSrvResponse_(const ContainerAllocator& _alloc)
    : error(0)  {
  (void)_alloc;
    }



   typedef int32_t _error_type;
  _error_type error;





  typedef boost::shared_ptr< ::ctrl_pkg::NavThrottleSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ctrl_pkg::NavThrottleSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct NavThrottleSrvResponse_

typedef ::ctrl_pkg::NavThrottleSrvResponse_<std::allocator<void> > NavThrottleSrvResponse;

typedef boost::shared_ptr< ::ctrl_pkg::NavThrottleSrvResponse > NavThrottleSrvResponsePtr;
typedef boost::shared_ptr< ::ctrl_pkg::NavThrottleSrvResponse const> NavThrottleSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ctrl_pkg::NavThrottleSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ctrl_pkg::NavThrottleSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ctrl_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ctrl_pkg': ['/home/deepracer/catkin_ws/src/ctrl_pkg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ctrl_pkg::NavThrottleSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ctrl_pkg::NavThrottleSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ctrl_pkg::NavThrottleSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ctrl_pkg::NavThrottleSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ctrl_pkg::NavThrottleSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ctrl_pkg::NavThrottleSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ctrl_pkg::NavThrottleSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d9e7447d5716e291370d8c7c21840938";
  }

  static const char* value(const ::ctrl_pkg::NavThrottleSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd9e7447d5716e291ULL;
  static const uint64_t static_value2 = 0x370d8c7c21840938ULL;
};

template<class ContainerAllocator>
struct DataType< ::ctrl_pkg::NavThrottleSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ctrl_pkg/NavThrottleSrvResponse";
  }

  static const char* value(const ::ctrl_pkg::NavThrottleSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ctrl_pkg::NavThrottleSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 error\n\
";
  }

  static const char* value(const ::ctrl_pkg::NavThrottleSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ctrl_pkg::NavThrottleSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavThrottleSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ctrl_pkg::NavThrottleSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ctrl_pkg::NavThrottleSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "error: ";
    Printer<int32_t>::stream(s, indent + "  ", v.error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CTRL_PKG_MESSAGE_NAVTHROTTLESRVRESPONSE_H
