// Generated by gencpp from file ctrl_pkg/NavThrottleSrvRequest.msg
// DO NOT EDIT!


#ifndef CTRL_PKG_MESSAGE_NAVTHROTTLESRVREQUEST_H
#define CTRL_PKG_MESSAGE_NAVTHROTTLESRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ctrl_pkg
{
template <class ContainerAllocator>
struct NavThrottleSrvRequest_
{
  typedef NavThrottleSrvRequest_<ContainerAllocator> Type;

  NavThrottleSrvRequest_()
    : throttle(0.0)  {
    }
  NavThrottleSrvRequest_(const ContainerAllocator& _alloc)
    : throttle(0.0)  {
  (void)_alloc;
    }



   typedef float _throttle_type;
  _throttle_type throttle;





  typedef boost::shared_ptr< ::ctrl_pkg::NavThrottleSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ctrl_pkg::NavThrottleSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct NavThrottleSrvRequest_

typedef ::ctrl_pkg::NavThrottleSrvRequest_<std::allocator<void> > NavThrottleSrvRequest;

typedef boost::shared_ptr< ::ctrl_pkg::NavThrottleSrvRequest > NavThrottleSrvRequestPtr;
typedef boost::shared_ptr< ::ctrl_pkg::NavThrottleSrvRequest const> NavThrottleSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ctrl_pkg::NavThrottleSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ctrl_pkg::NavThrottleSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ctrl_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ctrl_pkg': ['/home/deepracer/catkin_ws/src/ctrl_pkg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ctrl_pkg::NavThrottleSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ctrl_pkg::NavThrottleSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ctrl_pkg::NavThrottleSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ctrl_pkg::NavThrottleSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ctrl_pkg::NavThrottleSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ctrl_pkg::NavThrottleSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ctrl_pkg::NavThrottleSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a1a60fb29abbf31f24ecac8461e38a4f";
  }

  static const char* value(const ::ctrl_pkg::NavThrottleSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa1a60fb29abbf31fULL;
  static const uint64_t static_value2 = 0x24ecac8461e38a4fULL;
};

template<class ContainerAllocator>
struct DataType< ::ctrl_pkg::NavThrottleSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ctrl_pkg/NavThrottleSrvRequest";
  }

  static const char* value(const ::ctrl_pkg::NavThrottleSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ctrl_pkg::NavThrottleSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 throttle\n\
";
  }

  static const char* value(const ::ctrl_pkg::NavThrottleSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ctrl_pkg::NavThrottleSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.throttle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavThrottleSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ctrl_pkg::NavThrottleSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ctrl_pkg::NavThrottleSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "throttle: ";
    Printer<float>::stream(s, indent + "  ", v.throttle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CTRL_PKG_MESSAGE_NAVTHROTTLESRVREQUEST_H
