// Generated by gencpp from file ctrl_pkg/NavThrottleSrv.msg
// DO NOT EDIT!


#ifndef CTRL_PKG_MESSAGE_NAVTHROTTLESRV_H
#define CTRL_PKG_MESSAGE_NAVTHROTTLESRV_H

#include <ros/service_traits.h>


#include <ctrl_pkg/NavThrottleSrvRequest.h>
#include <ctrl_pkg/NavThrottleSrvResponse.h>


namespace ctrl_pkg
{

struct NavThrottleSrv
{

typedef NavThrottleSrvRequest Request;
typedef NavThrottleSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NavThrottleSrv
} // namespace ctrl_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ctrl_pkg::NavThrottleSrv > {
  static const char* value()
  {
    return "8ef012065533bc15e577d33d9dae2e5d";
  }

  static const char* value(const ::ctrl_pkg::NavThrottleSrv&) { return value(); }
};

template<>
struct DataType< ::ctrl_pkg::NavThrottleSrv > {
  static const char* value()
  {
    return "ctrl_pkg/NavThrottleSrv";
  }

  static const char* value(const ::ctrl_pkg::NavThrottleSrv&) { return value(); }
};


// service_traits::MD5Sum< ::ctrl_pkg::NavThrottleSrvRequest> should match 
// service_traits::MD5Sum< ::ctrl_pkg::NavThrottleSrv > 
template<>
struct MD5Sum< ::ctrl_pkg::NavThrottleSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ctrl_pkg::NavThrottleSrv >::value();
  }
  static const char* value(const ::ctrl_pkg::NavThrottleSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ctrl_pkg::NavThrottleSrvRequest> should match 
// service_traits::DataType< ::ctrl_pkg::NavThrottleSrv > 
template<>
struct DataType< ::ctrl_pkg::NavThrottleSrvRequest>
{
  static const char* value()
  {
    return DataType< ::ctrl_pkg::NavThrottleSrv >::value();
  }
  static const char* value(const ::ctrl_pkg::NavThrottleSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ctrl_pkg::NavThrottleSrvResponse> should match 
// service_traits::MD5Sum< ::ctrl_pkg::NavThrottleSrv > 
template<>
struct MD5Sum< ::ctrl_pkg::NavThrottleSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ctrl_pkg::NavThrottleSrv >::value();
  }
  static const char* value(const ::ctrl_pkg::NavThrottleSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ctrl_pkg::NavThrottleSrvResponse> should match 
// service_traits::DataType< ::ctrl_pkg::NavThrottleSrv > 
template<>
struct DataType< ::ctrl_pkg::NavThrottleSrvResponse>
{
  static const char* value()
  {
    return DataType< ::ctrl_pkg::NavThrottleSrv >::value();
  }
  static const char* value(const ::ctrl_pkg::NavThrottleSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CTRL_PKG_MESSAGE_NAVTHROTTLESRV_H
